version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: strava_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: strava_redis
    ports:
      - "6379:6379"

  server:
    build: ./server
    container_name: strava_server
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - GOOGLE_CLIENT_ID=${CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${CLIENT_SECRET}
      - FRONTEND_URL=http://${PUBLIC_IP}:3001
    ports:
      - "5000:5000"
    depends_on:
      - mongo


  chat_server:
    build: ./chat_server
    container_name: strava_chat
    ports:
      - "3000:3000"

    environment:
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379
      - PUBLIC_IP=${PUBLIC_IP}
    depends_on:
      - mongo
      - redis

  client:
    build:
      context: ./client
      args:
        - RESEND_API_KEY=${RESEND_API_KEY}
    container_name: strava_client
    environment:
      - PORT=3001
      - REACT_APP_API_URL=http://${PUBLIC_IP}:5000
      - REACT_APP_CHAT_URL=http://${PUBLIC_IP}:3000
      - RESEND_API_KEY=${RESEND_API_KEY}
    ports:
      - "3001:3001"

volumes:
  mongo_data: