name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }} # BURASI IP ADRESİ OLMALI (Secrets'ta düzelt)
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          if [ ! -d "strava-clone" ]; then
            git clone https://github.com/Alih2663/strava-clone.git strava-clone
          fi
          cd strava-clone
          git fetch origin main
          git reset --hard origin/main

          # BURADA PUBLIC_IP DOMAIN OLARAK SABİTLENDİ
          cat <<EOF > .env
          export EMAIL_FROM=${{ secrets.EMAIL_FROM }}
          MONGO_URI=${{ secrets.MONGO_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
          CLIENT_ID=${{ secrets.CLIENT_ID }}
          CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
          RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
          PUBLIC_IP=stravaclone.online
          EOF

          sudo docker-compose down || true
          
          # Build alırken PUBLIC_IP domain olarak gidiyor
          sudo PUBLIC_IP=stravaclone.online RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} docker-compose up -d --build
          
          sudo docker image prune -f