name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          if [ ! -d "strava-clone" ]; then
            git clone https://github.com/Alih2663/strava-clone.git strava-clone
          fi
          cd strava-clone
          git fetch origin main
          git reset --hard origin/main

          # Read secrets and create .env file
          cat <<EOF > .env
          MONGO_URI=${{ secrets.MONGO_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
          CLIENT_ID=${{ secrets.CLIENT_ID }}
          CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
          RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
          PUBLIC_IP=${{ secrets.EC2_HOST }}
          EOF

          sudo docker-compose --env-file .env up -d --build
          rm .env
          sudo docker image prune -f